### PR TITLE
Fix doc build

### PR DESCRIPTION
**Pull request by dstansby**
@bryan-harter this should fix the documentation build. I had to do a few things:

- Fix the xarray modules circular import by creating a new `cdf_factory.py` file
- Convert the `CDF` docstring into `numpydoc` format
- Remove some of the empty documentation files. I guess we can put these back with content eventually

### CODE REVIEW

**Comment by bryan-harter** [comment]
Will the cdflib.readthedocs.io automatically be updated?  

Also I realize now that you can actually click on the "Classes" on the current documentation and get a much, much more detailed view of the class.  So maybe the need to more docs isn't as urgent as I thought! For example I thought this was all we get about the cdfwrite class: https://cdflib.readthedocs.io/en/stable/modules/cdfwrite.html#

But instead we get all of this: https://cdflib.readthedocs.io/en/stable/api/cdflib.cdfwrite.CDF.html#cdflib.cdfwrite.CDF

**Comment by bryan-harter** [comment]
Also I've been testing out things on a different readthedocs site that I set up for testing purposes over here: 

cdf-lib.readthedocs.io

**Comment by dstansby** [comment]
It looks like cdflib.readthedocs.io doesn't have the right integration with github setup, and I don't have enough privledges here to set it up. If you let me know your username on readthedocs I can give you admin access to https://readthedocs.org/dashboard/cdflib so you can set it up

**Comment by bryan-harter** [comment]
I just log in with my github account, I think I think the username is just "bryan-harter"

**Comment by dstansby** [comment]
Fab, you should be added, and should be able to set up the webhook (and have other admin privileges too)

**Comment by bryan-harter** [comment]
Sounds good, I set it up to automatically deploy!  I added the autodoc stuff back in under "API Reference" (that seems to be what other libraries do with their documentation) after I got autodoc working again. 

One thing that confuses me is that lists somehow look different between my testing readthedocs site the real one: 

https://cdf-lib.readthedocs.io/en/latest/modules/cdfread.html#cdf-info
https://cdflib.readthedocs.io/en/stable/modules/cdfread.html#cdf-info

No idea what is up with that, but its a relatively minor issue for the moment

**Pull request merged**
