### PR TITLE
Fixed issue with unicode characters.

### PR DESCRIPTION
**Pull request by nickssl**
File "thg_l2_mag_han_20070517_v01.cdf" contains the Norwegian unicode character "\xf8" (latin small letter o with stroke) which crashes cdfread. This fixes the problem.

### CODE REVIEW

**Comment by nickssl** [comment]
I have found a better fix for this.

**Comment by dstansby** [comment]
Looking at https://docs.python.org/3/library/codecs.html#standard-encodings it seems like the encoding you've changed this to is Western Europe specific. I think we want to try and be more general than that, do you know if there's another more general encoding that would work?

**Comment by nickssl** [comment]
I don't think there is a more general encoding that would work. The incoming encoding is ASCII 8-bit. The high bytes can be any language. There is no way to know which language it is. The most common is Western European, since it includes some common accented latin letters.

One more general solution is to add a new keyword with default cp1252, ie change the definition of the function to:

def _read_data(self, byte_stream, data_type, num_recs, num_elems, dimensions=None, enc_in='cp1252'):

But then you also need to add this to many other places inside other functions, and since I am not a regular contributor I did not want to make extensive changes.

**Comment by nickssl** [comment]
Let me add that even my simpe change [decode('utf-8') to decode('cp1252')] is a big improvement, because the incoming encoding in not utf-8, it is 8-bit ascii. The existing decode('utf-8') crashes when there are Norwegian letters in the cdf. 

With my change decode('cp1252'), if you have non-western european characters (for example Russian characters) these characters will not crash the function, but also they will not show correctly. This is not ideal, but it is acceptable and in conformance with the latest cdf users' guide that states:

"Currently, the character set supported by the CDF is limited to ASCII set of characters. Non-conforming characters are either
rejected or will not be properly handled/displayed by the CDF library."

https://spdf.gsfc.nasa.gov/pub/software/cdf/doc/cdf380/cdf380ug.pdf

**Comment by nickssl** [comment]
Let me make clear that this issue is a bug. 

This:

byte_data[0:num_recs*num_elems].decode('utf-8')

assumes that you are reading utf-8 characters. 

This is not correct, you are reading 8-bit ascii. If the cdf contains only 7-bit ascii then this is identical to utf-8, so it does not cause any problems. But if the cdf file contains any characters beyond the first 128 ascii chars then it will crash. The majority of cdf files only contain 7-bit ascii (English), so this bug is not evident often.

**Comment by dstansby** [comment]
I think the best way forward here is to allow the user to set some sort of global encoding to read the file, and change the default behaviour to using ASCII, since that is what the CDF standard specifies. I appreciate that's not idea for your case, but at least then we are sticking to the standard, whilst giving users flexibility to read in non-conformant files.

Would you be happy to give this a go? It might be a big change, so no worries if not, I would be happy to take it on.

**Comment by nickssl** [comment]
I'd prefer you to do it, because I am not sure what exactly you want to do. I think that my simple solution is a good enough fix for the existing bug, but if you have something better in mind, that's great! 

Also, can you please point me to where is the "CDF standard" you refer to and which part mentions the attribute string encoding? The only relevant info I could find is the one I mentioned above, from the "cdf user's guide". Do you refer to the same document?  

The user's guide I mentioned above says the strings are ASCII. It does not say "extended ASCII", so I am not sure if this means that cdf files should only use the lower 128 ascii chars. In my understanding, it seem to imply that any characters beyond the lower 128 might not show correctly (which is exactly what my solution does) because if the cdf uses 256-chars ASCII then we don't know the encoding: 

"Currently, the character set supported by the CDF is limited to ASCII set of characters. Non-conforming characters are either
rejected or will not be properly handled/displayed by the CDF library."

But there might be some other document with a more precise definition of the CDF standard, I don't know.

**Comment by dstansby** [comment]
I've opened https://github.com/MAVENSDC/cdflib/pull/105 which allows one to open a CDF file with a user-specified encoding for strings, which I think is a bit more general than choosing a particular encoding.

Although what I can find of the CDF spec (https://spdf.gsfc.nasa.gov/pub/software/cdf/doc/cdf380/cdf38ifd.pdf) says the same as above re. only officially supporting ASCII characters, I think it's reasonable to default to UTF-8 as a superset of ASCII.

**Comment by bryan-harter** [comment]
See comment in #105

**Comment by dstansby** [comment]
I'm going to close this as I think `cdflib` adheres to the standard that says

> Non-conforming characters are either rejected or will not be properly handled/displayed by the CDF library."

and we give users the option to choose an encoding as of https://github.com/MAVENSDC/cdflib/pull/105

**Pull request closed without merging**
