### PR TITLE
Update online docs and module docstrings

### PR DESCRIPTION
**Pull request by mshumko**
I really enjoy using `cdflib`, but as a relatively new user I struggle to learn the library's features. My biggest hurdle is the documentation (or lack of). I'd like to help make cdflib more accessible by providing accurate and well-written online documentation.  

To that end, I went ahead and and began to update the Sphinx documentation and module doctrings. This PR is to gauge the interest of the cdflib developers to continue writing this documentation. Feel free to install my forked version to see the documentation. I can also attach screenshots.

# Summary of changes
1. Migrated the text from `introduction.rst` to `index.rst`.
2. Added the cdflib version, doc build date, and links to github and zenodo on the main page.
3. Began writing the `api.rst` to describe each module in detail.
4. Moved and edited the docstrings in `cdfread.py` and `epochs.py` such that Sphinx can correctly parse the documentation.

# Future changes
1. Finish editing the module docstrings and updating `api.rst` to cover all of the main functions.
2. Write an "Examples" section with complete examples on how to read a CDF file, parse CDF epochs, and write CDFs.
3. Move the "CDF Reader Class", "CDF Writer Class", and "CDF Time Conversions" documentation sections into one "Tutorial" section that will guide a new user through the `cdflib` library.

In the end, I aim to write documentation similar to the [sampex](https://sampex.readthedocs.io/en/latest/) package that I wrote not too long ago.

Thanks for writing this powerful package!

### CODE REVIEW

**Review by dstansby — APPROVED** [review]
Thanks so much for opening this PR! I'd definitely be super keen to see the documentation improved 👍

**Comment by dstansby** [comment]
If you've got more stuff please do put it in more PRs! Is there a bunch of work you'd like to do in quite quick succession? If so we can wait a little and do a new release of `cdflib` once it's done, or if not we could always do a few releases along the way - what do you think?

**Comment by mshumko** [comment]
Hi @dstansby, 

Thanks for the quick response! I plan to submit a few more PRs in the coming weeks, so we could wait a little before a new release.

It looks like the [readthedocs](https://readthedocs.org/projects/cdflib/builds/18873813/) build failed with the following (annotated) traceback.

`Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cdflib/envs/latest/lib/python3.9/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cdflib/checkouts/latest/doc/conf.py", line 21, in <module>
    import cdflib._version
ModuleNotFoundError: No module named 'cdflib._version'`

From reading the source code, `setuptools_scm` creates a dynamic version number during the pip install (i.e., `python3 -m pip install -e .`). However, the `readthedocs` build log only contains `...python -m pip install --exists-action=w --no-cache-dir -r doc/requirements.txt` where the `doc/requirements.txt` missing the `.` to install cdflib (and thus generate the `_version.py` module).

I think that adding a `.` in the `doc/requirements.txt` file is enough to build the documentation, but I wanted to confirm this before I submit a tiny follow-on PR.

**Comment by dstansby** [comment]
Ah, I think the right way to fix this would be to update the `readthedocs` config to install `cdflib` as part of the install step. https://docs.readthedocs.io/en/stable/config-file/v2.html#python should have instructions on how to do that.

At the same time it would be good to get rid of `requirements.txt`, and use the `docs` extra that's already defined in `setup.cfg`: https://github.com/MAVENSDC/cdflib/blob/161dc3281f65662e886c94862c4377107a16be70/setup.cfg#L43

**Pull request merged**
